<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>CollectionGallery.Shared</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Google.Cloud.Storage.V1" />
        <PackageReference Include="Microsoft.Extensions.Logging" />
    </ItemGroup>
</Project>